### ISSUE TITLE
getvars(::Formulation) should return a membersvector

### ISSUE THREAD

**Issue by vitornesello** [atoptima/Coluna.jl#106]
To avoid the need of both filters that take a tuple and the own object.
Currently it returns a VarDict

**Comment by vitornesello** [comment]
Not trivial do it directly.
I think that the best solution is to do the following change and keep only the standar filters where it takes a pair as input. This way we will be consistent throughout the code.
```julia
function Base.filter(f::Function, vec::MembersVector)
    MembersVector(vec.elements, Base.filter(e -> f(vec.elements[e[1]]), vec.records))
end
```
to
```julia
function Base.filter(f::Function, vec::MembersVector)
    MembersVector(vec.elements, Base.filter(f, vec.records))
end
```

**Comment by vitornesello** [comment]
Not trivial.
We could change:
```julia
function Base.filter(f::Function, vec::MembersVector)
    MembersVector(vec.elements, Base.filter(e -> f(vec.elements[e[1]]), vec.records))
end
```
to
```julia
function Base.filter(f::Function, vec::MembersVector)
    MembersVector(vec.elements, Base.filter(e -> f(Pair(e[1],vec.elements[e[1]])), vec.records))
end
````
where `e[1]` is the `Id` and `vec.elements[e[1]]` is the Variable itself.
But the thing get uglier and we will have to check if it allocates memory to do `Pair(e[1],vec.elements[e[1]])`

**Comment by guimarqu** [comment]
A way to solve this issue is to replace :
```julia
const VarDict = Dict{VarId,Variable}
```
by
```julia
struct VarDict
    variables:: Dict{VarId,Variable}
end
```
and do the same for constraints. What do you think about that @vitornesello ?

**Comment by vitornesello** [comment]
This seems good to me. I think it solves the problem
