### ISSUE TITLE
Issues with variable fixing

### ISSUE THREAD

**Issue by rrsadykov** [atoptima/Coluna.jl#1061]
There are some issus with variable fixing
- First, columns should never be fixed, as we cannot impose an upper bound on a column (it is too expensive to take into account the dual value associated with the upper bound in the pricing). So the `MasterColumnsRecord` and `unit_master_columns_record()` test should be modified. For me, we should only keep the set of active columns in `MasterColumnsRecord` without anything else.
- Second, there is now ambiguity between fixing a variable and deactivating it. For the moment, fixing deactivates the variable, but just deactivation does not fixes the variable. When variable is deactivated but not fixed, what does this mean? For me, this means that lower and upper bound are fixed to zero. Thus may be we should set bounds to zero when we just deactivate the variable? Because of this ambiguity I think that recording and restoring `StaticVarConstrUnit` is not done completely correctly, we should review it.

**Comment by guimarqu** [comment]
About the second point, 

For all variables, fixing => deactivation.

Deactivation means the variable is not part of the formulation anymore.
So when you deactivate, we ask the subsolvers to not consider the variable anymore.
It can mean you fix it to 0 but this is perhaps not the case everywhere. This is something to investigate.

Deactivation is mainly used to restore the state of a formulation when starting to evaluate a tree search node.
Also when cleaning up the master in column generation (currently unavailable). In the latter case, activating the master column variable when finding the same subproblem solution can be interpreted as an unfix.

**Comment by guimarqu** [comment]
So for the partial solution, I suggest to keep the fixed variables field :

https://github.com/atoptima/Coluna.jl/blob/b788c69212fc56442eb6e650e98ef7454b9aab97/src/MathProg/manager.jl#L50

but we indeed also need a new field to store the fixed lower bound on the variable.

We can have it in the FormulationManager, together with the set of fixed variables.
I'm open to a name better than "fixed lower bounds", or a name from the literature.
At the moment, we'll fix lower bounds only in the preprocessing.

**Comment by rrsadykov** [comment]
Ok for me. May call this field `fixed_part` or `partial_value`

**Comment by guimarqu** [comment]
go for partial_value

**Comment by rrsadykov** [comment]
Or we can have one field `partial_solution::Dict{VarId,Float64}` in `FormulationManager` instead of two fields `partial_value` and `fixed_vars`

**Comment by guimarqu** [comment]
I disagree because when the variable is fixed, we can deactivate it. This is not the case when it has a partial value. So I think we need to make a distinction.
