### ISSUE TITLE
Update/clean the code regarding the roles of algorithms/strategies

### ISSUE THREAD

**Issue by vitornesello** [atoptima/Coluna.jl#113]
- methods `run!(::AbstractAlgorithm)!` should only modify the formulations and should return an object of type `AbstractAlgorithmRecord`
- methods `apply!(::AbstractStrategy)` are allowed to modify the node according to the record returned by the algorithms.
- Should methods `prepare!(::AbstractAlgorithm)` create the object `AbstractAlgorithmData` and return it  to the function `apply!(::AbstractAlgorithm)`? `apply!(::AbstractAlgorithm)` would then call the methods `run!(::AbstractAlgorithm)` passing only the algorithm type and its data.

**Comment by guimarqu** [comment]
We should not have an object AbstractAlgorithmData. It is only needed by the algorithm and it should not be mandatory to have one.
