### ISSUE TITLE
bound changes are wrongly propagated

### ISSUE THREAD

**Issue by tbulhoes** [atoptima/Coluna.jl#121]
In a small GAP instance, I could observe the following behaviour. In the root, no bound is changed by preprocessing. The first child solved contains the branching constraint is x[1,7] <= 0. Then, preprocessing sets the ub of x[1,7] to 0. However, this bound change is not reverted before solving the second child (the one associated with x[1,7] >= 1) and thus preprocessing detects infeasibility.

**Comment by vitornesello** [comment]
For Representative Dutis. Related to #116

**Comment by vitornesello** [comment]
Fixed by #138 and #139
