### ISSUE TITLE
Variable added to master constraints with wrong coefficients

### ISSUE THREAD

**Issue by hhkramer** [atoptima/Coluna.jl#128]
In my Capacitated Lot Sizing application ([https://github.com/hhkramer/ColunaCodes/tree/master/CapacitatedLotSizing](url)) the coefficients of a new MC variable in the master capacity constraints are not being calculated considering both x and y variables from the corresponding subproblem. Thus, generated columns are added with wrong coefficients in such constraints.

To fix this I changed the `setprimalspsol!` function in formulation.jl replacing the following line:

`coef_matrix[constr_id, ps_id] = var_val * var_coef`

with

`coef_matrix[constr_id, ps_id] += var_val * var_coef`

After that, the application worked and the root node bound returned by coluna is correct (branch-and-price didn't work...)

Is this fix correct?

**Comment by vitornesello** [comment]
Yes, can you please open a PR with your fix?
