### ISSUE TITLE
Empty Conquer Strategy + NoBranching = infinite loop

### ISSUE THREAD

**Issue by guimarqu** [atoptima/Coluna.jl#166]
- New test to reproduce the bug
- Fix

**Comment by guimarqu** [comment]
Because of `reformulationsolver.jl:161`

```julia
    if !to_be_pruned(n)
        @logmsg LogLevel(-1) string("Node should not be pruned. Re-inserting in the tree.")
        push!(t, n)
    else
```
Maybe Coluna should consider a node pruned when the conquer strategy ends ?

**Comment by vitornesello** [comment]
This behavior was intended. If someone defines an empty strategies he must not expect to solve something
