### ISSUE TITLE
Not enough tests for set/get of Variables and Constraints

### ISSUE THREAD

**Issue by guimarqu** [atoptima/Coluna.jl#176]
`setcurkind` was not setting the bounds of `cur_data` at [0.0,1.0]. (fixed in benders branch).

~We should also discuss about this behavior :~  EDIT (03/02/2021) : handled by MOI (cf #436 #437).

```julia
    CL.setkind!(v_data, CL.Binary)
    @test CL.getkind(v_data) == CL.Binary
    @test CL.getlb(v_data) == 0.0
    @test CL.getub(v_data) == -113.0
```

**Comment by guimarqu** [comment]
@laradicp  do you think we can close this issue thanks to MOI tests ?

**Comment by laradicp** [comment]
> @laradicp do you think we can close this issue thanks to MOI tests ?

I don't know if get ConstraintDual and set ConstraintSet are considered related to this issue. If they are, maybe it could be closed after adding these two methods?

**Comment by guimarqu** [comment]
Ok yes they are kind of related but it's already in the TODO lists of MOI tests. Let's close.
