### ISSUE TITLE
Single variable objective function

### ISSUE THREAD

**Issue by phylosophys** [atoptima/Coluna.jl#181]
Salut,

I am trying to model a problem in which I have to minimize the max among a set of values. For example, I have the variables `s[k in K] >= 0` which may assume positive values, and the auxiliary variable `t >= 0`, then I have the constraint: `@constraint(model, auxmax[k in K], s[k] - t <= 0)`, and objective function: `@objective(model, Min, t)`.
When I try to solve such a model with Coluna I get the following error:
`The solver does not support an objective function of type MathOptInterface.SingleVariable`

Then, in an attempt to bypass this issue I tried to force the objective function to be a scalar affine function by doing the following:
+ Declare variable as: `@variable(model, t[i in 1:2] >= 0)`
+ Constraint: `@constraint(model, auxmax[k in K], s[k] - t[1] <= 0)`
+ Objective function: `@objective(model, Min, t[1] + 0*t[2])`

But I got another error: 
`BoundsError: attempt to access 0-element Array{Coluna.Variable,1} at index [1]`

This means that is not possible to model problems with such kind of objective functions?

--
Marcos

**Comment by guimarqu** [comment]
Hi Marcos,
You should be able to model any MILP.

The first issue will be easy to fix.

However, I would like to have the code that gave you the error message :
```
BoundsError: attempt to access 0-element Array{Coluna.Variable,1} at index [1]
```
It is a model without any decomposition ? (I'm afraid we did not test that case)

**Comment by phylosophys** [comment]
Hi Guillaume,

Sorry for the late reply.
Actually, it is an application using the Benders decomposition.

I have made modifications to the code, but I think I can reproduce the same case where I got the error mensage you need. I will let you know if I manage to do it.

Regards,
Marcos
