### ISSUE TITLE
Function naming decoration to alert for a `deepcopy` in the body

### ISSUE THREAD

**Issue by vitornesello** [atoptima/Coluna.jl#232]
It might be interesting to extend the `!` concept for when a function uses `deepcopy`. Like this:

* `function f(foo)` : No side-effects
* `function f!(foo)` : Side effects
* `function f!!(foo)` : Has `deepcopy` and likely side-effects

`deepcopy` can be quite dangerous and sometimes we fall in the trap of calling a function that `deepcopies` an argument and then use the `deepcopied` argument hoping the modifications would be persistent on the structures modified by the `deepcopying` function.

What do you think?

**Comment by guimarqu** [comment]
I don't think it's necessary if the documentation warns the user that the function performs a deepcopy.
