### ISSUE TITLE
`number_of_leaves` may return -1 but is used in a log function

### ISSUE THREAD

**Issue by guimarqu** [atoptima/Coluna.jl#242]
**Describe the bug**
The method `number_of_leaves` (`branchinggroup.jl:74`) may return -1 but its output is used in a log function without any checking.

See `score = - log(number_of_leaves(parent_delta, deltas)) / log(length(deltas))` (`branchinggroup.jl:147`)

**To Reproduce**
See the tests of PR #241

**Comment by rrsadykov** [comment]
Can you change `branchinggroup.jl:147` to
```
numleaves = number_of_leaves(parent_delta, deltas)
if numleaves < 0
    score = -Inf
else
    score = - log(numleaves) / log(length(deltas))
end
```
