### ISSUE TITLE
Check if column exists

### ISSUE THREAD

**Issue by vitornesello** [atoptima/Coluna.jl#249]
In the function that checks if column exists:
Will it work for non-binary variables?
Also, maybe it should be in a separate function.. We might have an isequal(varconstr, varconstr)

In this function :

https://github.com/atoptima/Coluna.jl/blob/8f7d105dd90b4ad9eb300d7ea883836882f33d45/src/MathProg/formulation.jl#L177

**Comment by guimarqu** [comment]
`setprimalsol!` does not work with binary variables... Like what you suggest, I think I will put the column checker as a separate method `exists` and let the algorithm decide if we allow duplicate columns or not.
