### ISSUE TITLE
Issue with projection from the reformulation to the original variables

### ISSUE THREAD

**Issue by persiflex** [atoptima/Coluna.jl#252]
> In fact the model as posted in atoptima/BlockDecomposition.jl#14 runs now without throwing the initial error 👏
> However, it is found infeasible and the centralized machines are not used.
> 
> ```
> Consumed 0.0 of machine c. Capacity is 1530.
> Consumed 0.0 of machine d. Capacity is 1190.
> Minimum capacity is 500.
> Not all jobs were assigned.
> Solution is not feasible. :(
> ```
> 
> Do you have an idea what could be the reason?

I have no idea. First, you should compute the objective function using the infeasible solution and check if Coluna found the same. If it's the case, the problem may come from the decomposition. Otherwise, it's when the solution is projected from the reformulation to the original vars.

You can print more logs using :
```julia
using Logging
global_logger(ConsoleLogger(stderr, LogLevel(-4)))
```

Please open an issue when you find the bug.

Thank you very much for your contribution to BlockDecomposition !

_Originally posted by @guimarqu in https://github.com/atoptima/BlockDecomposition.jl/pull/15#issuecomment-578894347_

Following up on this behavior identified in atoptima/BlockDecomposition.jl#14 , I'm now of the opinion that it's indeed a bug. Coluna does indeed find the same value for the objective function as is found for the original formulation without decomposition. However, the variables are not assigned the correct (and obviously internally identified) values. 

To replicate, please execute the attached script once with the boolean "decompose" set to true, once to false (l. 11f.) and compare the assignments x for the machines c and d (last two rows, which are all 0 when using Coluna.

[coluna_gap_v3_decompose-subsets.txt](https://github.com/atoptima/BlockDecomposition.jl/files/4218424/coluna_gap_v3_decompose-subsets.txt)

Would you have any indications for resolving this?

**Comment by guimarqu** [comment]
@persiflex  It should work well now !

**Comment by persiflex** [comment]
Great, it works now. Thanks a lot!
