### ISSUE TITLE
 Kind of a constraint in an MOIOptimizer

### ISSUE THREAD

**Issue by guimarqu** [atoptima/Coluna.jl#266]
PR #239  introduces an empty method `enforce_kind_in_optimizer!(form::Formulation, constr::Constraint)` symmetric to the one dedicated to variables.

What is the kind of a constraint in an MOIOptimizer ?

**Comment by guimarqu** [comment]
@rrsadykov @vitornesello @FD-V  Does the kind (facultative, core, subsystem) of a constraint can change ? I don't see any case in which it happens.

**Comment by guimarqu** [comment]
Same question for the `explicit` field

**Comment by rrsadykov** [comment]
I do not see neither.
