### ISSUE TITLE
Create the original formulation and then the Problem

### ISSUE THREAD

**Issue by guimarqu** [atoptima/Coluna.jl#268]
Steps :

- create the original formulation
- get the annotations
- create the Problem when we decompose

When `optimize` is called a second time : 
- update the original formulation
- update the annotations
- create the Problem for the new decomposition

We decompose from scratch each time the original formulation is updated (i.e. MOI.optimize! called).

**Comment by guimarqu** [comment]
@laradicp what do you think of this issue ? You worked on the "optimize twice" and it's working now.

**Comment by laradicp** [comment]
> @laradicp what do you think of this issue ? You worked on the "optimize twice" and it's working now.

There's still this bug related to "optimize twice": https://github.com/atoptima/Coluna.jl/blob/ec1fa6b6893721d9ae26f1db8a964de2cda27fcc/test/MathOptInterface/MOI_wrapper.jl#L248
I don't know why it doesn't work, but maybe this could be a fix.

**Comment by laradicp** [comment]
I don't think so, the sense is actually set correctly (I checked the Coluna sense after MOI.set and it was correct).
