### ISSUE TITLE
IP dual bound update

### ISSUE THREAD

**Issue by vitornesello** [atoptima/Coluna.jl#3]
@IssamT 

https://github.com/ResourceMind/Coluna.jl/blob/ae75caed1fe1797c613d3b1e094347693123ef9d/src/nodealgs/algevalnode.jl#L132

Shouldn't we pass the value of the primal solution? Since the primal solution of the LP is the dual bound for the IP.

**Comment by IssamT** [comment]
`dual_ip_bound` is actually a bad abuse of notation. We should change it at some point. Unlike `primal_ip_bound` We define `dual_ip_bound = ceil(dual_lp_bound)`, assuming we have only minimization

**Comment by vitornesello** [comment]
So `dual_lp_bound ` is the actual dual bound for the IP program?

**Comment by IssamT** [comment]
`dual_lp_bound` is the normal dual bound for the LP relaxation
