### ISSUE TITLE
Is Coluna possible to call solvers (e.g., Cplex, Gurobi) directly?

### ISSUE THREAD

**Issue by YP-Ye** [atoptima/Coluna.jl#301]
This problem may be a little strange. I have met a problem that I want to solve by Cplex or Gurobi in iterations 1-5, and then solve it by decomposition methods in the following iterations. Can it be realized by Coluna? I have not found the option to use Cplex or Gurobi directly.

**Comment by guimarqu** [comment]
Hi,

I’m not sure to understand what you want to do. 

One option is to create your model twice and apply the decomposition on the second one. You solve the first model using a MIP solver and the second one using Coluna.

A second option is to create a new algorithm that will solve the original formulation (it’s a field of `Reformulation`) using `SolveIpForm` and then call `ColGen`. There is an example in `tests/unit/algorithms/masteripheur.jl` where I create an algorithm. There is no doc at the moment and the algorithm submodule is a little bit messy.

**Comment by guimarqu** [comment]
The answer to the main question is yes.

**Comment by YP-Ye** [comment]
> Hi,
> 
> I’m not sure to understand what you want to do.
> 
> One option is to create your model twice and apply the decomposition on the second one. You solve the first model using a MIP solver and the second one using Coluna.
> 
> A second option is to create a new algorithm that will solve the original formulation (it’s a field of `Reformulation`) using `SolveIpForm` and then call `ColGen`. There is an example in `tests/unit/algorithms/masteripheur.jl` where I create an algorithm. There is no doc at the moment and the algorithm submodule is a little bit messy.

Thanks for your kindly reply. In my model, I add some constraints step by step, and in each step I want to use decomposition methods or Cplex directly. In the first step, I met a error:
`MethodError: no method matching store!(::Coluna.MathProg.Annotations, ::Nothing, ::Coluna.MathProg.Constraint)
`
I do not know whether it is a bug or it just cannot be solved by Coluna.

**Comment by guimarqu** [comment]
At the moment, Coluna does not support cut generation (it’s the next main feature we will implement) nor block generation at the user level.

How do you add your constraints ? It’s a cut generation or do you want to generate new subproblems during the optimization ?

Do you want to modify the model and restart the optimization ?

**Comment by YP-Ye** [comment]
> At the moment, Coluna does not support cut generation (it’s the next main feature we will implement) nor block generation at the user level.
> 
> How do you add your constraints ? It’s a cut generation or do you want to generate new subproblems during the optimization ?
> 
> Do you want to modify the model and restart the optimization ?

I just want to modify the model and restart the optimization like
`model = BlockModel(...)
for iter in 1:10
@constraint(model,...)
optimize!(model)
end
`
Actually in the first step, I met the error when I use Coluna. It can be solved by Cplex directly.

**Comment by guimarqu** [comment]
Ok this is because Coluna does not support problem modification (we actually didn't try). But I think it's not difficult to implement.

The error you get is because `BlockDecomposition` does not annotate the new constraint to say to which subproblem it belongs. I will look into this first bug.

**Comment by YP-Ye** [comment]
> Ok this is because Coluna does not support problem modification (we actually didn't try). But I think it's not difficult to implement.
> 
> The error you get is because `BlockDecomposition` does not annotate the new constraint to say to which subproblem it belongs. I will look into this first bug.

Thanks! Hope for your nice job.

**Comment by YP-Ye** [comment]
Here is a small example, which would reproduce the same error.
```
using JuMP
using Coluna, BlockDecomposition
using CPLEX

coluna = JuMP.optimizer_with_attributes(
            Coluna.Optimizer,
            "params" => Coluna.Params(
                solver = Coluna.Algorithm.SolveIpForm()
            ),
            "default_optimizer" => CPLEX.Optimizer
        )

model = BlockModel(coluna, bridge_constraints = false)

M = 1:10
@axis(N, 1:10)

@variable(model, x[i in M], Bin)
@variable(model, y[i in N], Bin)

@constraint(model, sum(x[i] for i in M) == 1)
@constraint(model, sum(y[i] for i in N) == 1)

@objective(model, Min, sum(x[i] for i in M) + sum(y[i] for i in N))

@dantzig_wolfe_decomposition(model, dec, N)
subproblems = BlockDecomposition.getsubproblems(dec)
optimize!(model)
```

**Comment by guimarqu** [comment]
Thank you !

There is a second bug. Anonymous constraints should be assigned to the master.

**Comment by guimarqu** [comment]
The bug from BlockDecomposition is fixed.

However, it's a little bit more complicated than what I thought.
It's related to https://github.com/atoptima/Coluna.jl/issues/268.

**Comment by guimarqu** [comment]
Hi,

I close this issue because we worked on problem update past few months.
Do not hesitate to create new issues if you face any problems.

Thanks for the report.
