### ISSUE TITLE
Pricing call back not working

### ISSUE THREAD

**Issue by guilhemdupuis** [atoptima/Coluna.jl#339]
Hello,

I am facing a problem with the demo of the pricing call back provided in Coluna's documentation. I have tried to stay as close as possible from the code provided, and in order to make things easier in a first time, the method solving the subproblems is based on mathematical programming.

However, I get the following error at the first iteration of the column generation:
```
ERROR: LoadError: MethodError: no method matching submit(::Model, ::BlockDecomposition.PricingSolution{Coluna.MathProg.PricingCallbackData}, ::Float64, ::Array{VariableRef,1}, ::Array{Int64,1})
Closest candidates are:
  submit(::MathOptInterface.Utilities.MockOptimizer, ::MathOptInterface.AbstractSubmittable, ::Any...) at /Users/Guilhem/.julia/packages/MathOptInterface/RmalA/src/Utilities/mockoptimizer.jl:529
  submit(::MathOptInterface.Utilities.CachingOptimizer, ::MathOptInterface.AbstractSubmittable, ::Any...) at /Users/Guilhem/.julia/packages/MathOptInterface/RmalA/src/Utilities/cachingoptimizer.jl:667
  submit(::MathOptInterface.Bridges.AbstractBridgeOptimizer, ::MathOptInterface.AbstractSubmittable, ::Any...) at /Users/Guilhem/.julia/packages/MathOptInterface/RmalA/src/Bridges/bridge_optimizer.jl:1195
```

Model and data are available on a single file at: https://drop.infini.fr/r/mZZ7fLvuky#camznVV9+aYNnso7sPWc/Tf9aFX04L0wh6JpQfu3pX4=

**Environment**
Julia: 1.3.1
Coluna: v0.3.0
GLPK: v0.12.1
BlockDecomposition: v1.2.0
MathOptInterface: v0.9.13
JuMP: v0.21.2

Best regards,

Guilhem

**Comment by guimarqu** [comment]
It's `MOI.submit!` because it changes your model.

**Comment by guilhemdupuis** [comment]
Thanks for the quick answer.

I've alredy tried with`MOI.submit!` but I get the same error message. I've changed it then to `MOI.submit` because I find no method called `MOI.submit!` but one is called `MOI.submit` (but I might have missed it).

**Comment by guimarqu** [comment]
Indeed, it's `MOI.submit` without the exaclamation mark. Do you mind editing the documentation ?

**Comment by guilhemdupuis** [comment]
Hmm actually even with `MOI.submit` the code doesn't run, so I don't know exactly what should be the documentation (in fact this was the initial point of my issue).

Do you have any other file/demo of the pricing callback so I could have look of the correct syntax? Thank you

**Comment by guimarqu** [comment]
If you replace `1`by `1.0` when you create sol_vals, does it work ?

**Comment by guilhemdupuis** [comment]
Indeed it works now! Thank you a lot :)

**Comment by guimarqu** [comment]
I reopen because we have to fix the documentation first.
