### ISSUE TITLE
How to set the coefficients of the objective function with the oracle

### ISSUE THREAD

**Issue by guilhemdupuis** [atoptima/Coluna.jl#349]
Hello,

Using Coluna with a pricing oracle, I would like the coefficients of the objective function to be computed by the oracle. In the demo for the generalized assignment problem, the coefficients are stored in the cost matrix from the instance, so I can’t find any example of this.

More precisely, I would like to formulate a vehicle routing problem with decision variables associated to the possible trips, which are generated by the oracle. The problem would be formulated like this, with `cost_h` the cost of the trip returned by the oracle and `α[i,h]` a binary vector indicating which customers are visited by this trip.

```
variables: x[h in Trips] in {0,1}
objective: min sum(cost_h * x[h] for h in Trips)
constraint: forall customer i, sum(x[h]*α[i,h] for h in Trips) == 1 
```
If this is possible with Coluna, how should be written the objective function?
Thank you very much.

**Comment by guimarqu** [comment]
Hi Guilhem,

Coluna does that for you.

If you look at the generalized assignment problem in the documentation, we provide to Coluna a compact formulation and a way to decompose it. 
Coluna then decomposes the compact formulation, it outputs a `Reformulation` that contains the master problem where variables (columns) describes assignment patterns for machine and subproblems which generates those patterns.

So the formulation you describe here is the master.

**Comment by rrsadykov** [comment]
Hi Guilhem,

You need to formulate your problem using arc variables. The only constraints you need are customer covering constrains. Other constraints may be skipped in the model, as they will be satisfied by the solutions returned by the pricing oracle.

Guillaume will soon do a vehicle routing demo for Coluna in order to illustrate cut separation.

**Comment by guilhemdupuis** [comment]
Thank you for your answers.

I already have implemented an arc based formulation for the CVRPTW, inspired from the GAP demo. You can find it attached if it useful for you (I have used Solomon instances with 25 customers and the oracle is just a call to a LP solver): [CVRPTW.zip](https://github.com/atoptima/Coluna.jl/files/4678481/CVRPTW.zip)

I would like now to implement a multi-trip VRP, therefore I though I would need decision variables for each trip. But if Coluna is supposed to do it on its own I will investigate on my side.

**Comment by guimarqu** [comment]
Everything fine ?

**Comment by guilhemdupuis** [comment]
So far no new problem to be reported but I didn't use Coluna much during the past weeks. I should come back on it soon, I keep you posted.

**Comment by guimarqu** [comment]
Hi,

I close this issue because it seems like there is no bug to fix here.
Do not hesitate to create new issues if you face any problems.

Thanks for the report.
