### ISSUE TITLE
Rename ConstrKind Core

### ISSUE THREAD

**Issue by guimarqu** [atoptima/Coluna.jl#356]
because of 

```
WARNING: both MathProg and Core export "Core"; uses of it in module Algorithm must be qualified
```

I suggest `Structural`. Any ideas ?

@rrsadykov @vitornesello @FD-V

**Comment by rrsadykov** [comment]
Sorry, I do not understand this issue. Can you give more details?

**Comment by guimarqu** [comment]
We have to write `Algorithm.Core` everytime we use it.

**Comment by rrsadykov** [comment]
Structural is ok. In our VRPSolver paper as also call these constraints "essential". I like essential more (structural for me is something stronger), but maybe Vitor and Francois have a different opinion.

**Comment by vitornesello** [comment]
I like essential better than structural

**Comment by FD-V** [comment]
good for me

**Comment by guimarqu** [comment]
New name will be `Essential`
