### ISSUE TITLE
Does not work with Julia 1.2

### ISSUE THREAD

**Issue by rrsadykov** [atoptima/Coluna.jl#357]
It seems Coluna does not work anymore with Julia 1.2:

```
julia> include("test/runtests.jl")
[ Info: Precompiling Coluna [88b4ec78-b192-11e8-04aa-4d367dd96a64]
ERROR: LoadError: Unable to import Bzip2_jll on Julia versions older than 1.3!
```

**Comment by guimarqu** [comment]
It doesn't work since the merge of robust cut callbacks into master ?

**Comment by rrsadykov** [comment]
yes

**Comment by rrsadykov** [comment]
I think this is because of this change : 

```
 deps = ["Bzip2_jll", "Libdl", "TranscodingStreams"]
-git-tree-sha1 = "2fee975d68f9a8b22187ae86e33c0829b30cf231"
+git-tree-sha1 = "2e62a725210ce3c3c2e1a3080190e7ca491f18d7"
 uuid = "523fee87-0ab8-5b00-afb7-3ecf72e48cfd"
-version = "0.7.1"
+version = "0.7.2"

```

**Comment by guimarqu** [comment]
is it working :  https://discourse.julialang.org/t/error-loaderror-unable-to-import-arpack-jll-on-julia-versions-older-than-1-3/34603/3 ?

Bzip2_jll is not a direct dependency of Coluna. We have to figure out if the Manifest is needed in the repo : https://discourse.julialang.org/t/does-manifest-toml-belong-in-the-repository/12029/3
(ping @vitornesello)

**Comment by rrsadykov** [comment]
Ok, it is working with `instantiate -p`. I did not know that.

**Comment by guimarqu** [comment]
Do we keep Manifest ? I vote for no because of the bug Ruslan had.
Moreover, there is no Manifest in JuMP, MathOptInterface, Tulip, LightGraphs.

**Comment by vitornesello** [comment]
I think we can remove it then. The downside is that we might have a bit more trouble to reproduce bugs.

**Comment by rrsadykov** [comment]
I vote to remove. I have troubles every time the manifest file changes. I need to add again GLPK, JuMP, ColunaDemos, etc.

**Comment by guimarqu** [comment]
We can ask people to upload the Manifest when they have a bug.

**Comment by guimarqu** [comment]
You will always need to add ColunaDemos. However, GLPK and JuMP are in dependencies of test.
