### ISSUE TITLE
Dict not threadsafe ?

### ISSUE THREAD

**Issue by guimarqu** [atoptima/Coluna.jl#363]
Hi @dianabarros @cristianabentes 

It looks like `Dict` is not threadsafe : https://discourse.julialang.org/t/can-dicts-be-threadsafe/27172/6

We have to init `Dict` or we could use an uninitialized array instead https://docs.julialang.org/en/v1/base/arrays/index.html#Core.Array-Tuple{UndefInitializer,Any}

**Comment by cristianabentes** [comment]
Thank you Guillaume for finding this problem. This is very useful for our parallelization work.

However, the last bug that I sent you was happening on the sequential execution.

**Comment by guimarqu** [comment]
@cristianabentes yes it's not related to your bug. I'll open a pull request to merge a code snippet in your branch to write the subproblem in a file when it is detected as infeasible. 

@dianabarros I was talking about these lines :
https://github.com/atoptima/Coluna.jl/blob/a148dd11510ae5c6a3388b130eced7de05bd012f/src/Algorithm/colgen.jl#L379-L384

but it looks like @rrsadykov fixed this in PR #348

**Comment by cristianabentes** [comment]
> @cristianabentes yes it's not related to your bug. I'll open a pull request to merge a code snippet in your branch to write the subproblem in a file when it is detected as infeasible.

We merge our code with the master branch yesterday to perform new tests, and now the instance gapC-10-100 doesn't find a solution and terminates very quickly:
***************************************************************************************
**** BaB tree root node
**** Local DB = 0.0000, global bounds : [ 0.0000 , Inf ], time = 0.00 sec.
***************************************************************************************
┌ Warning: Solver has no result to show.
└ @ Coluna.MathProg ~/.julia/dev/Coluna.jl/src/MathProg/optimizerwrappers.jl:185
┌ Warning: Solver returned that LP restricted master is infeasible or unbounded (feasibility status = INFEASIBLE) during phase != 1.
└ @ Coluna.Algorithm ~/.julia/dev/Coluna.jl/src/Algorithm/colgen.jl:538
Node is already conquered. No children will be generated
[ Info: Terminated
[ Info: Primal bound: Inf
[ Info: Dual bound: Inf

**Comment by guimarqu** [comment]
Ok I’ll try to reproduce the bug tomorrow.

**Comment by guimarqu** [comment]
Closed by #348
