### ISSUE TITLE
Bug with low optimality tolerance

### ISSUE THREAD

**Issue by rrsadykov** [atoptima/Coluna.jl#370]
Node is not cut by bound when column generation is stopped with the gap less than optimality tolerance.

To reproduce, run test "gap with all phases in col.gen" with optimality_tol = 1e-5.

**Comment by guimarqu** [comment]
Method `to_be_pruned` in `Algorithm/node.jl:60` does not take into account the optimality tolerance of the conquer algorithm called.
We should have something like : 
```julia
 isapprox(bounds_ratio, 1) || ip_gap(nodestate) < optimality_tolerance
```

However, what should be the value of `optimality_tolerance` if several optimization algorithms have such an attribute ? I think we should let the conquer algorithm tell to the `TreeSearchAlgorithm` whether the node is pruned. What do you think ?  (cc @FD-V  @vitornesello )

**Comment by rrsadykov** [comment]
I think optimality tolerance should be a global parameter (as well as feasibility, integrality tolerances). 
Then we can add these tolerances into `OptimizationState` so the every optimization algorithm know them. Or we should pass tolerances as an input. 

We can also have a special structure with global parameters and pass this structure as an input to all algorithms. To this structure we can also add starting time to track the time limit, etc.

**Comment by guimarqu** [comment]
I agree that we should have a global default optimality tolerance but we must be able to relax the optimality tolerance of some specific algorithms. So the optimality tolerance should be a parameter of each algorithm and I suggest to add a field in `OptimizationOutput` that will be `true` if the dual bound reached the primal bound (given the relaxed tolerance) in the conquer algorithm.  

TreeSearch will prune the node iff the value of the latter field is equal to `true`.

**Comment by rrsadykov** [comment]
However, if you relax tolerance for example in column generation, you cannot guarantee that the global tolerance of the branch-and-price is satisfied, i.e. the algorithm is not exact (up to the global tolerance) anymore. Or I miss something? @guimarqu @FD-V

**Comment by guimarqu** [comment]
Yes that's true. 

We may display a warning when Conquer returns that dual bound reached primal bound subject but TreeSearch considers that the node is not pruned. It may happen when tolerance of the conquer is larger than tolerance of the treesearch (and that's currently the case).

**Comment by rrsadykov** [comment]
Can you give me a "use case" when one wants to relax the optimality tolerance in a child algorithm?

**Comment by guimarqu** [comment]
A subgradient followed by simplexe colgen ?

**Comment by rrsadykov** [comment]
Ok for me. An alternative of adding a field to `OptimizationOutput` is to set the optimality status in `OptimizationState`. The the tree search algorithm then checks the status the node. If it is optimum, but node cannot be pruned by the optimality tolerance of the tree search, the warning is shown.

**Comment by rrsadykov** [comment]
The tree search algorithm should also track the worst dual bound of all pruned nodes, so that the correct dual bound is returned at the end.

**Comment by guimarqu** [comment]
> Ok for me. An alternative of adding a field to `OptimizationOutput` is to set the optimality status in `OptimizationState`. The the tree search algorithm then checks the status the node. If it is optimum, but node cannot be pruned by the optimality tolerance of the tree search, the warning is shown.

Yes I also thought of this. I think we can borrow few statuses from MOI (ref https://jump.dev/MathOptInterface.jl/stable/apireference/#Termination-Status-1). We should also take a look at issue #80 (& fix it).

**Comment by rrsadykov** [comment]
Status of the node is in its `OptimizationState`.
