### ISSUE TITLE
Error After "using" in Julia 1.0.5

### ISSUE THREAD

**Issue by rafaelmartinelli** [atoptima/Coluna.jl#373]
After installing Coluna and BlockDecomposition using Julia 1.0.5 on both Windows and Linux, I get the following error:

Windows:
![image](https://user-images.githubusercontent.com/10237929/84702073-74219080-af2c-11ea-8e4f-0313e8e7386b.png)

Linux:
![image](https://user-images.githubusercontent.com/10237929/84702175-974c4000-af2c-11ea-9e21-07311ea0b98a.png)

Please let me know if you need more information.

**Comment by guimarqu** [comment]
Hi,

Thank you for reporting this issue.

It looks like `Base.@kwdef` works for julia 1.1 and above only.

Two options : 
1. drop support of Julia 1.0 (and LTS version)
2. use `with_kw` from `Parameters.jl` (and add a new dependency).

I'm in favor of option 2 ( @rrsadykov @vitornesello what do you think ?).

Source : https://discourse.julialang.org/t/kwdef-not-working-for-parametric-struct/25286

**Comment by rrsadykov** [comment]
Yes, I am for option 2 too (if `@with_kw` has the same functionality as `@kwdef`). We also need to release 0.3.1  with this correction (I suppose there is a bunch of people using Julia 1.0) and we need to add Julia 1.0.5 to tests.

**Comment by guimarqu** [comment]
Yes for sure, it's a critical bug.
