### ISSUE TITLE
Names of variables are not informative anymore

### ISSUE THREAD

**Issue by rrsadykov** [atoptima/Coluna.jl#378]
Example in generalized assignment tests:

`**** Branching constraint: var_6>=1.0`

should be 

`**** Branching constraint: x[2,3]>=1.0`

**Comment by guimarqu** [comment]
If you try with `model, x, dec = CLD.GeneralizedAssignment.model(data, coluna, false)` is it working ?

**Comment by guimarqu** [comment]
> If you try with `model, x, dec = CLD.GeneralizedAssignment.model(data, coluna, false)` is it working ?

Doesn't work on my computer.

I'll fix this next week.

**Comment by guimarqu** [comment]
Fixed by #380 

You have to create a direct model to have the names in Coluna : 

https://github.com/atoptima/ColunaDemos.jl/blob/eb642e06a4bd9927ed4ef31f099f86deac6bbfcd/src/GeneralizedAssignment/model.jl#L4-L7
