### ISSUE TITLE
Set a gap limit in B&P

### ISSUE THREAD

**Issue by guilhemdupuis** [atoptima/Coluna.jl#417]
Hello,

Just a simple question about Coluna optimizer attributes: is it possible to set a gap limit to stop the Branch & Price procedure when the primal and the dual bounds are close enough?

Thank you in advance.
Best,

GD

**Comment by guimarqu** [comment]
Hi Guilhem,

It will be available in master when we'll merge the PR mentioned above.

**Comment by guilhemdupuis** [comment]
Thanks Guilllaume, great !
