### ISSUE TITLE
Activating smoothing stabilization results in unfeasible solution

### ISSUE THREAD

**Issue by guilhemdupuis** [atoptima/Coluna.jl#421]
Hello,

I have set the smoothing stabilization parameter to 0.5 for a CVRPTW problem and obtain an unfeasible solution with an objective value lower than the optimal solution (from the litterature).

Is it something to expect with stabilization or there might be a bug somewhere? I can provide the sources if need be.

Thanks,

GD

**Comment by rrsadykov** [comment]
Normally, stabilization should work just by setting the corresponding parameter. This might be a bug. Can you provide instructions how to reproduce this issue?

**Comment by guilhemdupuis** [comment]
Hello,
Unfortunately, I didn't retrieve the configuration I've used, and I wasn't able to reproduce the issue this morning. So, I assume this was just a mistake from me and I have post this issue too quickly. I am sorry for the inconvenience!

**Comment by rrsadykov** [comment]
Ok, I close this issue then. Do not hesitate to open another if you have a similar issue in the future.
