### ISSUE TITLE
ArgumentError  with Cplex

### ISSUE THREAD

**Issue by wdscoelho** [atoptima/Coluna.jl#446]
Hello,

After updating Coluna v0.3.3 -> 0.3.5, I'm no longer able to solve any model with Cplex (12.10; CPLEX.jl = v0.6.6)
I'm getting the following message : 

`ArgumentError: ModelLike of type CPLEX.Optimizer does not support accessing the attribute MathOptInterface.ConstraintBasisStatus(1)
`

It works fine with GPLK.
 
Wesley

**Comment by guimarqu** [comment]
Hi, Coluna now retrieves the `ConstraintBasisStatus` when it computes the value of the dual solution from the subsolver (Cplex here). It looks like `MOI.ConstraintBasisStatus` is supported since CPLEX.jl v0.7.0 (https://github.com/jump-dev/CPLEX.jl/releases/tag/v0.7.0). Can you try with this version ?

**Comment by wdscoelho** [comment]
It works with CPLEX v0.7.3

Thank you.

**Comment by guimarqu** [comment]
Nice thank you !

**Comment by ysu1028** [comment]
> It works with CPLEX v0.7.3
> 
> Thank you.

Hello, I met the same problem, and I would like to know how you update the cplex from v.0.6.6 to v.0.7.3? I'm not very familiar with julia, and I use the following comments which give me another error:

import Pkg
Pkg.add(Pkg.PackageSpec(name = "CPLEX", rev = "master"))


ERROR: Unsatisfiable requirements detected for package MathOptInterface [b8f27783]:
 MathOptInterface [b8f27783] log:
 ├─possible versions are: [0.5.0-0.5.1, 0.6.0-0.6.4, 0.7.0, 0.8.0-0.8.4, 0.9.0-0.9.20] or uninstalled
 ├─restricted to versions 0.9.19-0.9 by CPLEX [a076750e], leaving only versions 0.9.19-0.9.20
 │ └─CPLEX [a076750e] log:
 │   ├─possible versions are: 0.7.7 or uninstalled
 │   └─CPLEX [a076750e] is fixed to version 0.7.7
 └─restricted to versions 0.9.18 by an explicit requirement — no versions left

**Comment by wdscoelho** [comment]
Hello,

You can update by typing `Pkg.update("CPLEX")`

**Comment by ysu1028** [comment]
> Hello,
> 
> You can update Cplex by typing `Pkg.update("CPLEX")`
> 
> I have MathOptInterface v0.9.14.
> Try `Pkg.update("MathOptInterface ")` if needed.

Thank you very much for this very quick reply, I tried Pkg.update("CPLEX"), but its version still stay at v.0.6.6 and my MathOptInterface version is v.0.9.20. 
Here is the list of my package status:

  Status `~/.julia/environments/v1.1/Project.toml`
  [c52e3926] Atom v0.12.21
  [9e28174c] BinDeps v1.0.1
  [6cde8614] BlockDecomposition v1.2.5
  [a076750e] CPLEX v0.6.6
  [336ed68f] CSV v0.6.1
  [88b4ec78] Coluna v0.3.6
  [a93c6f00] DataFrames v0.20.2
  [864edb3b] DataStructures v0.17.20
  [31c24e10] Distributions v0.23.8
  [e30172f5] Documenter v0.25.3
  [90d7349d] Erdos v0.7.0
  [587475ba] Flux v0.10.3
  [60bf3e95] GLPK v0.13.0
  [28b8d3ca] GR v0.52.0
  [ed2ffb44] GeneticAlgorithms v0.0.0 [`~/.julia/dev/GeneticAlgorithms`]
  [a2cc645c] GraphPlot v0.4.2
  [2e9cd046] Gurobi v0.8.1
  [f67ccb44] HDF5 v0.12.5
  [7073ff75] IJulia v1.22.0
  [682c06a0] JSON v0.21.1
  [0f8b85d8] JSON3 v1.4.0
  [4076af6c] JuMP v0.21.4
  [e5e0dc1b] Juno v0.8.4
  [b964fa9f] LaTeXStrings v1.2.0
  [fc18253b] LazyJSON v0.2.2
  [093fc24a] LightGraphs v1.3.3
  [2f5eb75a] LightGraphsFlows v0.4.1
  [b8f27783] MathOptInterface v0.9.20
  [44063525] NODAL v0.4.0
  [429524aa] Optim v0.20.1
  [69de0a69] Parsers v1.0.11
  [91a5bcdd] Plots v1.10.6+ #340cd0a (https://github.com/JuliaPlots/Plots.jl)
  [d330b81b] PyPlot v2.9.0
  [e6cf234a] RandomNumbers v1.4.0
  [90137ffa] StaticArrays v0.12.5
  [2913bbd2] StatsBase v0.32.2
  [735ffce8] TrafficAssignment v0.6.3
  [8c8f4381] TravelingSalesmanHeuristics v0.3.2 [`~/.julia/dev/TravelingSalesmanHeuristics`]
  [b8865327] UnicodePlots v1.3.0
  [ade2ca70] Dates 
  [de0858da] Printf 
  [8dfed614] Test 

I tried again this command to update cplex:

import Pkg
Pkg.add(Pkg.PackageSpec(name = "CPLEX", rev = "master"))

and I got:
ERROR: Unsatisfiable requirements detected for package CuArrays [3a865a2d]:
 CuArrays [3a865a2d] log:
 ├─possible versions are: [0.2.1, 0.3.0, 0.4.0, 0.5.0, 0.6.0-0.6.2, 0.7.0-0.7.3, 0.8.0-0.8.1, 0.9.0-0.9.1, 1.0.0-1.0.2, 1.1.0, 1.2.0-1.2.1, 1.3.0, 1.4.0-1.4.7, 1.5.0, 1.6.0, 1.7.0-1.7.3, 2.0.0-2.0.1, 2.1.0, 2.2.0-2.2.2] or uninstalled
 ├─restricted by compatibility requirements with CEnum [fa961155] to versions: [0.2.1, 0.3.0, 0.4.0, 0.5.0, 0.6.0-0.6.2, 0.7.0-0.7.3, 0.8.0-0.8.1, 0.9.0-0.9.1, 1.0.0-1.0.2, 1.1.0, 1.2.0-1.2.1, 2.2.0-2.2.2] or uninstalled
 │ └─CEnum [fa961155] log:
 │   ├─possible versions are: [0.1.0-0.1.2, 0.2.0, 0.3.0, 0.4.0-0.4.1] or uninstalled
 │   └─restricted to versions [0.3.0-0.3, 0.4.0-0.4] by CPLEX [a076750e], leaving only versions [0.3.0, 0.4.0-0.4.1]
 │     └─CPLEX [a076750e] log:
 │       ├─possible versions are: 0.7.7 or uninstalled
 │       └─CPLEX [a076750e] is fixed to version 0.7.7
 └─restricted by compatibility requirements with Flux [587475ba] to versions: [1.6.0, 1.7.0-1.7.3] — no versions left
   └─Flux [587475ba] log:
     ├─possible versions are: [0.4.1, 0.5.0-0.5.4, 0.6.0-0.6.10, 0.7.0-0.7.3, 0.8.0-0.8.3, 0.9.0, 0.10.0-0.10.4, 0.11.0-0.11.6] or uninstalled
     └─restricted to versions 0.10.3 by an explicit requirement, leaving only versions 0.10.3

It's now conflict with cuarrays....

Best,
Yue

**Comment by ysu1028** [comment]
> Nice thank you !

Hello,

I met a similar problem and I created an issue (https://github.com/atoptima/Coluna.jl/issues/465#issue-830237348)
Could you have a look at it? Thank you!

Best,
Yue

**Comment by wdscoelho** [comment]
Yes, that's one of the downsides of Julia.
Try to remove the packages that are causing "Unsatisfiable requirements" by `Pkg.remove("CuArrays")` for example and install them after installing Cplex.
You have to find a good version of each version to each package so they all work fine together.

Here's my package status

>  Status `/raid/home/wesley/.julia/environments/v1.2/Project.toml`
>   [7c4d4715] AmplNLWriter v0.6.0
>   [6cde8614] BlockDecomposition v1.2.4
>   [a076750e] CPLEX v0.7.3
>   [336ed68f] CSV v0.7.7
>   [e2554f3b] Clp v0.8.0
>   [88b4ec78] Coluna v0.3.5 #change_logs (https://github.com/atoptima/Coluna.jl.git)
>   [a93c6f00] DataFrames v0.21.7
>   [864edb3b] DataStructures v0.17.20
>   [31c24e10] Distributions v0.23.11
>   [8f5d6c58] EzXML v1.0.0
>   [60bf3e95] GLPK v0.13.0
>   [aa1b3936] GraphIO v0.5.0
>   [a2cc645c] GraphPlot v0.4.2
>   [86223c79] Graphs v0.10.3
>   [7073ff75] IJulia v1.21.3
>   [6deec6e2] IndexedTables v0.13.0
>   [b6b21f68] Ipopt v0.6.3
>   [4138dd39] JLD v0.10.0
>   [4076af6c] JuMP v0.21.1
>   [093fc24a] LightGraphs v1.3.3
>   [2f5eb75a] LightGraphsFlows v0.3.1
>   [9c8b4983] LightXML v0.8.1
>   [b8f27783] MathOptInterface v0.9.14
>   [fdba3010] MathProgBase v0.7.8
>   [626554b9] MetaGraphs v0.6.5
>   [6c89ec66] MolecularGraph v0.3.2
>   [0db19996] NBInclude v2.2.0
>   [fae87a5f] ParserCombinator v2.0.0
>   [58dd65bb] Plotly v0.3.0 #master (https://github.com/plotly/Plotly.jl)
>   [91a5bcdd] Plots v1.0.14
>   [438e738f] PyCall v1.92.2
>   [ae029012] Requires v1.0.2
>   [699a6c99] SimpleTraits v0.9.3
>   [47aef6b3] SimpleWeightedGraphs v1.1.1
>   [2913bbd2] StatsBase v0.33.2
>   [b4f28e30] TikzGraphs v1.1.0
>   [37f6aa50] TikzPictures v3.3.0
>   [a759f4b9] TimerOutputs v0.5.6
>   [fdbf4ff8] XLSX v0.7.3
>   [9a3f8284] Random
>   [10745b16] Statistics
>

**Comment by ysu1028** [comment]
> Yes, that's one of the downsides of Julia.
> Try to remove the packages that are causing "Unsatisfiable requirements" by `Pkg.remove("CuArrays")` for example and install them after installing Cplex.
> You have to find a good version of each package so they all work fine together.
> 
> Here's my package status
> 
> > Status `/raid/home/wesley/.julia/environments/v1.2/Project.toml`
> > [7c4d4715] AmplNLWriter v0.6.0
> > [6cde8614] BlockDecomposition v1.2.4
> > [a076750e] CPLEX v0.7.3
> > [336ed68f] CSV v0.7.7
> > [e2554f3b] Clp v0.8.0
> > [88b4ec78] Coluna v0.3.5 #change_logs (https://github.com/atoptima/Coluna.jl.git)
> > [a93c6f00] DataFrames v0.21.7
> > [864edb3b] DataStructures v0.17.20
> > [31c24e10] Distributions v0.23.11
> > [8f5d6c58] EzXML v1.0.0
> > [60bf3e95] GLPK v0.13.0
> > [aa1b3936] GraphIO v0.5.0
> > [a2cc645c] GraphPlot v0.4.2
> > [86223c79] Graphs v0.10.3
> > [7073ff75] IJulia v1.21.3
> > [6deec6e2] IndexedTables v0.13.0
> > [b6b21f68] Ipopt v0.6.3
> > [4138dd39] JLD v0.10.0
> > [4076af6c] JuMP v0.21.1
> > [093fc24a] LightGraphs v1.3.3
> > [2f5eb75a] LightGraphsFlows v0.3.1
> > [9c8b4983] LightXML v0.8.1
> > [b8f27783] MathOptInterface v0.9.14
> > [fdba3010] MathProgBase v0.7.8
> > [626554b9] MetaGraphs v0.6.5
> > [6c89ec66] MolecularGraph v0.3.2
> > [0db19996] NBInclude v2.2.0
> > [fae87a5f] ParserCombinator v2.0.0
> > [58dd65bb] Plotly v0.3.0 #master (https://github.com/plotly/Plotly.jl)
> > [91a5bcdd] Plots v1.0.14
> > [438e738f] PyCall v1.92.2
> > [ae029012] Requires v1.0.2
> > [699a6c99] SimpleTraits v0.9.3
> > [47aef6b3] SimpleWeightedGraphs v1.1.1
> > [2913bbd2] StatsBase v0.33.2
> > [b4f28e30] TikzGraphs v1.1.0
> > [37f6aa50] TikzPictures v3.3.0
> > [a759f4b9] TimerOutputs v0.5.6
> > [fdbf4ff8] XLSX v0.7.3
> > [9a3f8284] Random
> > [10745b16] Statistics

Thank you very much, it seems gurobi works on my computer. I'll try to remove the conflicting package. In fact I feel very strange because I haven't installed these package (like CuArrays) and I have no idea why it conflicts...

Have a nice day!

Best,
Yue
