### ISSUE TITLE
ArgumentError: ModelLike of type CPLEX.Optimizer does not support accessing the attribute MathOptInterface.ConstraintBasisStatus(1)

### ISSUE THREAD

**Issue by ysu1028** [atoptima/Coluna.jl#465]
**Describe the bug**
Hello,

I'm using Coluna.jl and I call Cplex as solver to solve the master problem and sub-problem. My julia version is 1.1.1 and I use Macbook for programming. Then I met the error reported as below:

ArgumentError: ModelLike of type CPLEX.Optimizer does not support accessing the attribute MathOptInterface.ConstraintBasisStatus(1)

I referred to the solution: https://github.com/atoptima/Coluna.jl/issues/446 and I use the following command to update the version of CPLEX from v.0.6.6 to v.0.7.0:

import Pkg
Pkg.add(Pkg.PackageSpec(name = "CPLEX", rev = "master"))

and I got another error:
ERROR: Unsatisfiable requirements detected for package MathOptInterface [b8f27783]:
 MathOptInterface [b8f27783] log:
 ├─possible versions are: [0.5.0-0.5.1, 0.6.0-0.6.4, 0.7.0, 0.8.0-0.8.4, 0.9.0-0.9.20] or uninstalled
 ├─restricted to versions 0.9.19-0.9 by CPLEX [a076750e], leaving only versions 0.9.19-0.9.20
 │ └─CPLEX [a076750e] log:
 │   ├─possible versions are: 0.7.7 or uninstalled
 │   └─CPLEX [a076750e] is fixed to version 0.7.7
 └─restricted to versions 0.9.18 by an explicit requirement — no versions left

Is there anyone who experienced a similar problem and can give me some advice? I'll be very grateful if someone can help me!

Best,
Yue

**Comment by guimarqu** [comment]
Hi,

I think you should try to upgrade Cplex.jl using :

```
] add Cplex@0.7
```

in the Julia REPL.

**Comment by ysu1028** [comment]
> Hi,
> 
> I think you should try to upgrade Cplex.jl using :
> 
> ```
> ] add Cplex@0.7
> ```
> 
> in the Julia REPL.

Thank you so much for the quick reply! I've tried but it gives me error:

ERROR: Unsatisfiable requirements detected for package CuArrays [3a865a2d]:
 CuArrays [3a865a2d] log:
 ├─possible versions are: [0.2.1, 0.3.0, 0.4.0, 0.5.0, 0.6.0-0.6.2, 0.7.0-0.7.3, 0.8.0-0.8.1, 0.9.0-0.9.1, 1.0.0-1.0.2, 1.1.0, 1.2.0-1.2.1, 1.3.0, 1.4.0-1.4.7, 1.5.0, 1.6.0, 1.7.0-1.7.3, 2.0.0-2.0.1, 2.1.0, 2.2.0-2.2.2] or uninstalled
 ├─restricted by compatibility requirements with Flux [587475ba] to versions: [1.6.0, 1.7.0-1.7.3]
 │ └─Flux [587475ba] log:
 │   ├─possible versions are: [0.4.1, 0.5.0-0.5.4, 0.6.0-0.6.10, 0.7.0-0.7.3, 0.8.0-0.8.3, 0.9.0, 0.10.0-0.10.4, 0.11.0-0.11.6] or uninstalled
 │   └─restricted to versions 0.10.3 by an explicit requirement, leaving only versions 0.10.3
 ├─restricted by julia compatibility requirements to versions: [0.2.1, 0.3.0, 0.4.0, 0.5.0, 0.6.0-0.6.2, 0.7.0-0.7.3, 0.8.0-0.8.1, 0.9.0-0.9.1, 1.0.0-1.0.2, 1.1.0, 1.2.0-1.2.1, 1.3.0, 1.4.2-1.4.7, 1.5.0, 1.6.0] or uninstalled, leaving only versions: 1.6.0
 └─restricted by compatibility requirements with CEnum [fa961155] to versions: [0.2.1, 0.3.0, 0.4.0, 0.5.0, 0.6.0-0.6.2, 0.7.0-0.7.3, 0.8.0-0.8.1, 0.9.0-0.9.1, 1.0.0-1.0.2, 1.1.0, 1.2.0-1.2.1, 2.2.0-2.2.2] or uninstalled — no versions left
   └─CEnum [fa961155] log:
     ├─possible versions are: [0.1.0-0.1.2, 0.2.0, 0.3.0, 0.4.0-0.4.1] or uninstalled
     └─restricted by compatibility requirements with CPLEX [a076750e] to versions: [0.3.0, 0.4.0-0.4.1]
       └─CPLEX [a076750e] log:
         ├─possible versions are: [0.3.3, 0.4.0-0.4.4, 0.5.0-0.5.1, 0.6.0-0.6.6, 0.7.0-0.7.6] or uninstalled
         └─restricted to versions 0.7 by an explicit requirement, leaving only versions 0.7.0-0.7.6

**Comment by guimarqu** [comment]
I saw your comments in the other issue. You can also try to create a new environment for your project :

https://julialang.github.io/Pkg.jl/v1.5/environments/

**Comment by ysu1028** [comment]
> I saw your comments in the other issue. You can try to fix the dependencies in your default environment or you can try to create a new environment for your project :
> 
> https://julialang.github.io/Pkg.jl/v1.5/environments/

Hello,

Thank you for your suggestion, the problem has been fixed :-)

By the way, I'm now using Coluna to solve the MIP by decomposition into master problem and sub-problem. But strangely, the results I got from coluna when primal bound = dual bound is not the same as I got from using solver to solve directly. I'm solving Dial-a-ride problem with electric vehicles.... and I think the constraints and variables are well defined with the index k (means vehicle) as the first index. I really have no idea why coluna gives me a wrong optimal solution... What do you think would be a reason for that?

Thank you again and looking from your response! I believe your comments will be very helpful for me!

Best,
Yue

**Comment by guimarqu** [comment]
Hi,

Do you run the exact same model ?

Is the "optimal" solution returned by Coluna feasible ?

Where does the dual bound exceeds the optimal solution value ? The `branchingtreefile` option in `TreeSearchAlgorithm` will allow you to visualize the branch and bound tree : https://atoptima.github.io/Coluna.jl/stable/dev/algorithms/#Coluna.Algorithm.TreeSearchAlgorithm)

Do you use multiplicity  ? (cf https://atoptima.github.io/Coluna.jl/stable/user/start/ : `specify!.(subproblems, lower_multiplicity = 0, upper_multiplicity = 1)`)

I close this issue because the initial problem is fixed. You can open a new issue if you want to pursue the conversation.

**Comment by ysu1028** [comment]
> Hi,
> 
> Do you run the exact same model ?
> 
> Is the "optimal" solution returned by Coluna feasible ?
> 
> Where does the dual bound exceeds the optimal solution value ? The `branchingtreefile` option in `TreeSearchAlgorithm` will allow you to visualize the branch and bound tree : https://atoptima.github.io/Coluna.jl/stable/dev/algorithms/#Coluna.Algorithm.TreeSearchAlgorithm)
> 
> Do you use multiplicity ? (cf https://atoptima.github.io/Coluna.jl/stable/user/start/ : `specify!.(subproblems, lower_multiplicity = 0, upper_multiplicity = 1)`)
> 
> I close this issue because the initial problem is fixed. You can open a new issue if you want to pursue the conversation.



> Hi,
> 
> Do you run the exact same model ?
> 
> Is the "optimal" solution returned by Coluna feasible ?
> 
> Where does the dual bound exceeds the optimal solution value ? The `branchingtreefile` option in `TreeSearchAlgorithm` will allow you to visualize the branch and bound tree : https://atoptima.github.io/Coluna.jl/stable/dev/algorithms/#Coluna.Algorithm.TreeSearchAlgorithm)
> 
> Do you use multiplicity ? (cf https://atoptima.github.io/Coluna.jl/stable/user/start/ : `specify!.(subproblems, lower_multiplicity = 0, upper_multiplicity = 1)`)
> 
> I close this issue because the initial problem is fixed. You can open a new issue if you want to pursue the conversation.

Thank you very much for the reply!

Yes, I checked carefully my constraints, it seems that all the vehicle-related constraints should be indexed by k (representing the kth vehicle) and this index should be the first index in the model.  Otherwise, coluna cannot recognize the sub-problem correctly. After realizing this, I changed one constraint that is vehicle-related but not indexed by k (because it is not necessary) and I can now get right results.

Thank you again for your suggestion, I'll think over them while constructing model with coluna.

Best,
Yue

**Comment by guimarqu** [comment]
It's good to read to you could fix your issue ! 
Best.
