### ISSUE TITLE
no method matching getincumbents(::Coluna.Algorithm.Node)

### ISSUE THREAD

**Issue by isaiasfsilva** [atoptima/Coluna.jl#476]
I'm using the version 0.3.6.

**Error 1 (using the TreeSearchAlgorithm with some parameters) :**
MethodError: no method matching getincumbents(::Coluna.Algorithm.Node)
Closest candidates are:
  getincumbents(!Matched::Coluna.Algorithm.OptimizationState) at /home/isaias/localSoftwares/julia-1.1.0/Packages/packages/Coluna/vvtFO/src/Algorithm/utilities/optimizationstate.jl:145

**Error 2 (using the standard config as illustrated in the "getting start" guide):** 
ArgumentError: ModelLike of type CPLEX.Optimizer does not support accessing the attribute MathOptInterface.ConstraintBasisStatus(1)

Ps.: It works perfectly in the version 0.3.1 using the standard config. I updated to use the "ColCutGenConquer" in the parameters (not implemented in the version 0.3.1).

**Comment by guimarqu** [comment]
Hi,

Error 1 : Do you use the best dual bound explore strategy ? If yes, it has been fixed (cf #414 and associated PR)  but I didn't release the patch. I'll release the patch as soon as you confirm it is the same bug.

Error 2 : What version of Cplex do you use ? (cf #446)
