### ISSUE TITLE
Log message for infeasible node

### ISSUE THREAD

**Issue by hhkramer** [atoptima/Coluna.jl#511]
**Describe the bug**
When solving my application with Coluna, some nodes are clearly infeasible (the dual bound value indicates that there are artificial variables in the master solution), but there is no message saying that the node is infeasible. Messages indicating why a node was pruned would help to keep track of the tree.

**To Reproduce**
```console
julia src/CapacitatedLotSizing/scripts/runsingleinstance.jl testSmall
```
Run with the following parameters (disabled primal heuristics):
```julia
coluna = optimizer_with_attributes(
        Coluna.Optimizer,
        "params" => Coluna.Params(
            solver = Coluna.Algorithm.TreeSearchAlgorithm(
                conqueralg = Coluna.Algorithm.ColCutGenConquer(
                    primal_heuristics = Coluna.Algorithm.ParameterisedHeuristic[])
            ) # default BCP
        ),
        "default_optimizer" => Gurobi.Optimizer # GLPK for the master & the subproblems
    )
```

**Expected behavior**
The following is shown in the log:
```console
***************************************************************************************
**** BaB tree node N° 8, parent N° 2, depth 2, 2 open nodes
**** Local DB = 73.5556, global bounds : [ 73.5556 , 79.0000 ], time = 16.09 sec.
**** Branching constraint: v<=0.0
***************************************************************************************
  <it=  1> <et=16.10> <mst= 0.00> <sp= 0.01> <cols= 0> <al= 0.00> <DB= 1385.9057> <mlp= 1385.9057> <PB=79.0000>
[ Info: Dual bound reached primal bound.
Node is already conquered. No children will be generated.
***************************************************************************************
```
There is a message to indicate that the node is conquered, but not because of infeasibility.

Also, it seems that the following message is not associated with the node:
```console
[ Info: Dual bound reached primal bound.
```

**Environment (please complete the following information):**
 - Julia version 1.6.0
 - OS: Windows 10 64bits
 - Coluna version 0.3.7 #master

**Comment by guimarqu** [comment]
Hi @hhkramer , it looks like you did not push the file `src/CapacitatedLotSizing/scripts/runsingleinstance.jl`.

**Comment by hhkramer** [comment]
> Hi @hhkramer , it looks like you did not push the file `src/CapacitatedLotSizing/scripts/runsingleinstance.jl`.

Hi @guimarqu , it is there as you can see below:

![image](https://user-images.githubusercontent.com/48336700/115867240-34132000-a411-11eb-8038-5cd83796a1c1.png)

I did a new push yesterday, did you pull it?

**Comment by guimarqu** [comment]
Indeed @hhkramer , I was on the wrong branch haha

**Comment by hhkramer** [comment]
> Indeed @hhkramer , I was on the wrong branch haha

hehehehe No problem!

**Comment by guimarqu** [comment]
I could reproduce the bug.

```
  <it=  1> <et=20.52> <mst= 0.04> <sp= 0.00> <cols= 0> <al= 0.00> <DB= 7577.5000> <mlp= 7577.5000> <PB=79.0000>
get_best_lp_primal_sol(cg_optstate) = Primal solution
| MC_5000004 = 0.25
| MC_4000005 = 1.0
| MC_5000005 = 0.75
| local_art_of_branch_leq_3_v = 0.75
└ value = 7577.50 
```

**Comment by rrsadykov** [comment]
I think we should be careful here.  To check whether a node is infeasible, you need to do additional work, so this harms the performance. Most users will not care for what reason the node was pruned, so for them the current behaviour is ok.

May be we need to have a parameter in `ColumnGeneration` which will force to run phase 1 if there are artificial variables in the solution (which by default will be false)?

**Comment by guimarqu** [comment]
Yes you're right. Avoiding extra computational work to prove infeasibility is one of the advantages of using a mixed phase 1 & 2. If we always run the phase 1 after the mixed phase returned a lp solution with artificial variables while the node has been pruned, we loose this advantage.

Do we need this parameter or it's only for very specific use cases ?
@hhkramer why do you need to prove infeasibility ?
