### ISSUE TITLE
Branching priorities

### ISSUE THREAD

**Issue by rrsadykov** [atoptima/Coluna.jl#521]
In our problem we would need to give different branching priorities for different variables.  I will be able to modify `VarBranchingRule` algorithm for that myself. However, I would need to retrieve the name of a variable (without indices), given by the user in JuMP. Is it possible now?

**Comment by guimarqu** [comment]
It's not possible at the moment except if you extract it with a regex.
How the user defines the branching priorities ?

**Comment by rrsadykov** [comment]
Extracting with regex would be ok. Can you add such a method to `MathProg`?

For branching priorities, we should add field `varname` to `VarBranchingRule` (empty name would be branching on all variables as it is now). Then the user would add several `VarBranchingRule`s to vector `rules` together with priorities to `StrongBranching`. Probably  `StrongBranching` should be renamed just to `Branching`.

**Comment by guimarqu** [comment]
@rrsadykov May I let you do the changes in the branching algorithm and open a PR to merge into master ? I'll tag 0.3.9 just after.

**Comment by rrsadykov** [comment]
Implemented in pull request #528
