### ISSUE TITLE
Possibility to return primal and dual bounds in the pricing callback

### ISSUE THREAD

**Issue by rrsadykov** [atoptima/Coluna.jl#527]
For the moment, the user returns just the solution and the solution value (primal bound) in the pricing callback. We have also the convention that the user callback is exact if and only if `cb.stage == 1` (in version 0.4).  In this case the dual bound is set equal to the primal bound. Otherwise, no dual bound is passed to the column generation. 

For more flexible behaviour, we should provide the user the possibility to return also the dual bound. If dual bound is set equal to primal bound, then the solution is provably optimal. Otherwise, this is a heuristic solution. This way, heuristic/exact pricing is not attached anymore to the column generation stage. Also, the user will have a possibility to pass information about the dual bound even if it is not equal to the primal bound. This information then may be used by column generation to update the dual bound of the master problem even during the heuristic stage.

**Comment by guimarqu** [comment]
I think it should be addressed at the same time : 

If user may define several solvers, he can define several callbacks (one heuristic and second exact). This way we can avoid `stage` parameter: user will just define `optimizer_id=2` and `optimizer_id=3`. @guimarqu, what do you think about this?

_Originally posted by @rrsadykov in https://github.com/atoptima/Coluna.jl/pull/534#discussion_r638972099_

**Comment by guimarqu** [comment]
Implemented in #641
