### ISSUE TITLE
Improve tests

### ISSUE THREAD

**Issue by vitornesello** [atoptima/Coluna.jl#57]
- [ ] Write unit tests for missing files
- [x] Fix issue where codecov misses lines that are actually not missed by the tests
- [x] Add tests with different objective sense + constraint sense
- [x] silence Logger output

**Comment by guimarqu** [comment]
Merge #59  ends the second task.

**Comment by vitornesello** [comment]
PR's https://github.com/atoptima/Coluna.jl/pull/71 (open) and https://github.com/atoptima/Coluna.jl/pull/65 (merged) solve third task

**Comment by vitornesello** [comment]
Fourth task is solved by PR #81

**Comment by guimarqu** [comment]
I'll create a project for this.
