### ISSUE TITLE
Constraint on variable overwritten

### ISSUE THREAD

**Issue by laradicp** [atoptima/Coluna.jl#583]
**Describe the bug**
When adding a new constraint on variable, it may overwrite previous constraints of the same type.

**To Reproduce**
```julia
# x >= 1
c1 = MOI.add_constraint(
    model,
    MOI.SingleVariable(x),
    MOI.GreaterThan(1),
)
# x >= 2
c2 = MOI.add_constraint(
    model,
    MOI.SingleVariable(x),
    MOI.GreaterThan(2),
)
```
Impossible to delete `c2` without losing `c1` because `Coluna._constraint_on_variable!` called by `MOI.add_constraint` changes the perennial bounds of the variables.

**Additional context**
Maybe related to the incomplete dual solution (missing `MOI.ConstraintDual` for `SingleVariable` constraints) and to https://github.com/atoptima/Coluna.jl/issues/531.

**Comment by guimarqu** [comment]
Coluna will now an error `MOI.LowerBoundAlreadySet`. (see #628)
