### ISSUE TITLE
Access to dual value of constraints of the master problem

### ISSUE THREAD

**Issue by diHnguyen** [atoptima/Coluna.jl#591]
Hello,

I would like to access the duals associated with the constraints in the master problem for a separate model, and it seems like I can't if they are added as lazy constraints. (I could be completely wrong about this, but I did not see a solution when looking into the topic.) 

Would it be possible to iteratively add constraints to the master problem without the use of lazy constraints, perhaps something similar to @constraint() in JuMP? 

Thank you so much!

**Comment by guimarqu** [comment]
Hello,

The only way to generate constraints during optimization is to use the method `MOI.submit` in a pricing callback (non-lazy or user cuts).
At the moment, it's indeed not possible to retrieve the dual of the constraint added during the optimisation.
However, last month, we implemented a feature (#547) which will allow us to implement this very easily.

As the next 2/3 weeks are going to be busy, I don't think I'll have time to implement that and write the tests.
If you need this feature very quickly, I would be very grateful if you could share a very little example with some expected dual values of the constraints. I'll put this example in the unit tests and I'll make it work in the master branch.

Thanks for the report !

**Comment by guimarqu** [comment]
Hi, 

thanks for the MWE,

In the tests, you have an example of how you can retrieve the dual value of the cut : 

The callback

https://github.com/atoptima/Coluna.jl/blob/d79d546ebc7e43791d445f4fbbfb1a8cb33868b0/test/issues_tests.jl#L432-L443

The line to get the dual value

https://github.com/atoptima/Coluna.jl/blob/d79d546ebc7e43791d445f4fbbfb1a8cb33868b0/test/issues_tests.jl#L450

**Comment by diHnguyen** [comment]
This is wonderful! Thank you!!
