### ISSUE TITLE
Subroblem membership

### ISSUE THREAD

**Issue by IssamT** [atoptima/Coluna.jl#6]
The var and constr membership defined in Coluna can only store linear membership. Subroblems can be non linear. Only their contribution in the master is required to be linear. And I believe only the latter need to be known by coluna while the subroblem own membership can be directly passed to the MOI solver without being stored in coluna. Am I wrong?

**Comment by IssamT** [comment]
@francois-DV, @rrsadykov, what do you think about this?

**Comment by rrsadykov** [comment]
I think you are right. At least in BapCod, all memberships are linear, as we use a MILP (Mixed-Integer Linear Programming) solver to solve the master and subproblems. If subproblem has non-linear constraints, it can only be solved by a custom solver.
Another question is whether you want to allow user to define non-linear constraints in Coluna, i.e. if there are applications like that you absolutely want to support.

**Comment by vitornesello** [comment]
@rrsadykov @artalvpes @guimarqu @FD-V  can we think about this issue again after the discussions that we had about modeling?

**Comment by guimarqu** [comment]
Stale as we redesigned the base data struct
