### ISSUE TITLE
Bug in strong branching

### ISSUE THREAD

**Issue by rrsadykov** [atoptima/Coluna.jl#601]
In `src/Algorithm/branching/branchingalgo.jl`, there is a bug in line 106. Instead 

`if length(groups) <= nb_candidates_for_next_phase `

one should put

`if phase_index > 1 && length(groups) <= nb_candidates_for_next_phase`

Otherwise no children are generated in the strong branching in some cases and we loose optimality.

**Comment by guimarqu** [comment]
It looks like https://github.com/atoptima/Coluna.jl/pull/568/commits/c187d6b7a21c9ba3de0d1684968a1ebeefd2dafc was solving the same issue. What version should we keep?

**Comment by guimarqu** [comment]
Ok, let's keep the safe option then: generation of children in phase 1. Thanks!
