### ISSUE TITLE
getsolutions

### ISSUE THREAD

**Issue by Ishaanjolly** [atoptima/Coluna.jl#652]
I tried to implement this standard example from the documentation. 
```
nb_machine_types = 2;
nb_jobs = 10;
J = 1:nb_jobs;
Q = [10, 15];
U = [3, 2];  # 3 machines of type 1 & 2 machines of type 2
c = [10 11 13 11 12 14 15 8 9 11; 20 21 23 21 22 24 25 18 19 21];
w = [4 4 5 4 4 3 4 5 6 5; 5 5 6 5 5 4 5 6 7 6];

using JuMP, GLPK;

T1 = [1, 2, 3]; # U[1] machines
T2 = [4, 5]; # U[2] machines
M = union(T1, T2);
m2t = [1, 1, 1, 2, 2]; # machine id -> type id

model = Model(GLPK.Optimizer);
@variable(model, x[M, J], Bin); # 1 if job j assigned to machine m
@constraint(model, cov[j in J], sum(x[m,j] for m in M) == 1);
@constraint(model, knp[m in M], sum(w[m2t[m],j] * x[m,j] for j in J) <= Q[m2t[m]]);
@objective(model, Min, sum(c[m2t[m],j] * x[m,j] for m in M, j in J));

optimize!(model);
objective_value(model)

using BlockDecomposition, Coluna, JuMP, GLPK;
const BD = BlockDecomposition

coluna = optimizer_with_attributes(
    Coluna.Optimizer,
    "params" => Coluna.Params(
        solver = Coluna.Algorithm.TreeSearchAlgorithm() # default BCP
    ),
    "default_optimizer" => GLPK.Optimizer # GLPK for the master & the subproblems
);

@axis(T, 1:nb_machine_types);

model = BlockModel(coluna);
@variable(model, x[T, J], Bin); # 1 if job j assigned to machine m
@constraint(model, cov[j in J], sum(x[t,j] for t in T) == 1);
@constraint(model, knp[t in T], sum(w[t] * x[t,j] for j in J) <= Q[t]);
@objective(model, Min, sum(c[t,j] * x[t,j] for t in T, j in J));

@dantzig_wolfe_decomposition(model, dec_on_types, T);
sps = getsubproblems(dec_on_types)
for t in T
    specify!(sps[t], lower_multiplicity = 0, upper_multiplicity = U[t]);
end
getsubproblems(dec_on_types)
optimize!(model);

for t in T
    assignment_patterns = BD.getsubproblems(model, t);
    for pattern in assignment_patterns
        nb_times_pattern_used = BD.value(pattern);
        jobs_in_pattern = [];
        for j in J
            if BD.value(pattern, x[t, j]) ≈ 1
                push!(jobs_in_pattern, j);
            end
        end
        println("Pattern of machine type $t used $nb_times_pattern_used times : $jobs_in_pattern");
    end
end

```
I am getting 'ERROR: LoadError: UndefVarError: getsolutions not defined'. Is this something that's expected?

**Comment by guimarqu** [comment]
I could reproduce with the last version of Coluna/BlockDecomposition. It is not expected and I'm quite surprised that was not raised during tests.

**Comment by guimarqu** [comment]
> I could reproduce with the last version of Coluna/BlockDecomposition. It is not expected and I'm quite surprised that was not raised during tests.

No sorry, I misread, I did not get the same error:
> ERROR: LoadError: MethodError: no method matching getsubproblems(::Model, ::BlockDecomposition.AxisId{:T, Int64})
Stacktrace:
 [1] top-level scope
   @ ~/Downloads/tests-0.4/test2.jl:53

You should replace the line with `BD.getsolutions(model, t)`.

And you'll get this output:

```
Pattern of machine type 1 used 1.0 times : Any[8, 9]
Pattern of machine type 1 used 1.0 times : Any[1, 2]
Pattern of machine type 1 used 1.0 times : Any[4, 5]
Pattern of machine type 2 used 1.0 times : Any[3, 7, 10]
Pattern of machine type 2 used 1.0 times : Any[6]
```

So it works with the latest versions of Coluna (0.4) and BlockDecomposition (1.7)

**Comment by Ishaanjolly** [comment]
Strange, it still shows the same for me. No idea why. This is post replacing that line. 
<img width="666" alt="Screenshot 2022-04-01 at 13 00 56" src="https://user-images.githubusercontent.com/71589295/161216407-bd80108a-5636-440f-ad6b-c291de3d708a.png">

**Comment by guimarqu** [comment]
Strange indeed, there is no stack trace?
Are you using Coluna 0.4 & BlockDecomposition 1.7? (you can check by going ] st in the julia repl)

**Comment by Ishaanjolly** [comment]
I have older versions, perhaps that might be the case? 

<img width="666" alt="Screenshot 2022-04-01 at 13 09 58" src="https://user-images.githubusercontent.com/71589295/161217859-3c84379d-4902-4189-8ab9-46a40ef8c5e6.png">

**Comment by guimarqu** [comment]
Yes, you have old versions of Coluna and BlockDecomposition. You should update or you can force the installation of the latest versions `add Coluna@0.4.0`.
