### ISSUE TITLE
Deletion callback for storage units

### ISSUE THREAD

**Issue by artalvpes** [atoptima/Coluna.jl#755]
Storage units  will be used in [ColunaVrpSolver](https://github.com/atoptima/ColunaVrpSolver.jl) to store C++ pointers to heap allocated memory. This memory should be manually deleted when the corresponding branch-and-bound node (and all its descendants) has already been conquered. A special callback function is required to allow the user application to do this deletion.

**Comment by guimarqu** [comment]
Hey Artur,

We should not manage memory in Coluna. I recommend using a finalizer instead.
You wrap the pointer in a mutable struct and define the finalizer that will call a C method that deletes the pointer.

```julia
mutable struct A
       a
       function A(a)
           b = new(a)
           finalizer(_ -> println("finalize!"), b)
       end
end
```

```julia
julia> function f()
           a = A(1)
           b = A(2)
           return 1
       end
f (generic function with 1 method)

julia> f()
1

julia> GC.gc()
finalize!
finalize!
```

I'm not 100% sure about when finalizers are called though. I could not find documentation other than the docref.
