### ISSUE TITLE
The pricing solver not returning any solution leads to an error message

### ISSUE THREAD

**Issue by artalvpes** [atoptima/Coluna.jl#758]
**Describe the bug**
When the pricing solver returns no solution, Coluna gives an error message stating that the subproblem is infeasible. This is not necessarily the case. In case of stages, the princing solver may have run only its heuristic version which was unable to find any feasible solution. It may also be the case that all solutions have been fixed by reduced cost, meaning that no improving solution could be found for the master but not meaning that the whole subproblem is infeasible.

**To Reproduce**
TODO. Any example where the pricing solver returns no solution at some point. Using pricing stages would help.

**Expected behavior**
The same behavior as for the case that no solution returned by pricing solver could be inserted in the master: `[ Info: No new column generated by the pricing problems.`

**Environment (please complete the following information):**
 - Julia version 1.8.1
 - OS: MacOs

**Comment by guimarqu** [comment]
We need to write a test to make sure it's not happening anymore in the new implementation of the column generation.

**Comment by guimarqu** [comment]
@artalvpes, can you confirm that the test in `gap_with_pricing_callback_and_stages` ensures that this bug is not happening anymore?

**Comment by artalvpes** [comment]
Yes. I confirm.
