### ISSUE TITLE
Suggestion: rename Phase 3 to Phase 0 in ColGen

### ISSUE THREAD

**Issue by enjoyUrFruits** [atoptima/Coluna.jl#952]
In ColGen Phases, we use Phase 3 in addition of classic Phase 1 and Phase 2. This is a bit disturbing because Phase 3 is used ahead of Phase 1 and Phase 2.
I suggest to rename Phase 3 to "Phase 0" for greater understanding of the phases mechanic.

**Comment by rrsadykov** [comment]
This phase is a mix of Phase 1 and 2. So, an alternative would be "1A2" phase (we use this is BaPCod). But I am ok with Phase 0 if it is explained in documentation that this is a "mixed 1 and 2 phase".
