### ISSUE TITLE
Refactoring of ColCutGenConquer

### ISSUE THREAD

**Issue by najaverzat** [atoptima/Coluna.jl#954]
ColCutGenConquer is currently the default conquer algorithm used in ```TreeSearch```. The doc -- and maybe the method itself -- needs a refactoring:

- parameter ```stages``` has been removed from the algo but not from the doc
- using this algorithm as the default conquer of ```TreeSearch``` is a questionable choice as it can't be used with Benders. Maybe we should create a "real" default conquer that could be used no matter the decomposition and then let the user choosing a specific conquer

**Comment by guimarqu** [comment]
Done in #1017
